added mk2 tints to es_extended
esx-framework/esx-core pull request #754
Opened 2022-12-18 11:59 UTC by PreacherDev

2022-12-20 21:16 UTC, Rav3n95 commented
Has to be a better way to do that, its must be working. But nothing else

2022-12-21 20:21 UTC, iSentrie commented
> Has to be a better way to do that, its must be working. But nothing else

first of all why this is a bad way to do it?

2022-12-23 11:19 UTC, PreacherDev commented
its basically just using other table keys.

2023-01-08 17:20 UTC, mcNuggets1 commented
How about you just make a different table for it, instead of writing in the same

2023-01-08 21:21 UTC, PreacherDev commented
the one who writing on this script could've implemented it long time ago.

2023-01-08 21:22 UTC, mcNuggets1 commented
> the one who writing on this script could've implemented it long time ago.

Still for backwards compatibility (eg scripts relying on the old table), you should make a new table and call it like MK2WeaponTints

2023-01-08 21:24 UTC, PreacherDev commented
that is definitely a good idea yes. they could do it if its not done on the latest version, many people would like to have it

2023-01-09 22:24 UTC, Gellipapa reviewed
@PreacherDev Hi! Yes I also think that a separate board would be the solution. If you update the es_textend it will work as it is, there should be no restrictions! If you doing these changes please update your branch and fix merge issues thank you.

2023-01-10 14:26 UTC, iSentrie requested changes
...

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +	},
```suggestion
	[0] = TranslateCap('tint_default'),
	[1] = TranslateCap('tint_green'),
	[2] = TranslateCap('tint_gold'),
	[3] = TranslateCap('tint_pink'),
	[4] = TranslateCap('tint_army'),
	[5] = TranslateCap('tint_lspd'),
	[6] = TranslateCap('tint_orange'),
	[7] = TranslateCap('tint_platinum')
}

Config.MK2WeaponTints = {
	[0]  = TranslateCap('tint_classic_black'),
	[1]  = TranslateCap('tint_classic_gray'),
	[2]  = TranslateCap('tint_classic_two_tone'),
	[3]  = TranslateCap('tint_classic_white'),
	[4]  = TranslateCap('tint_classic_beige'),
	[5]  = TranslateCap('tint_classic_green'),
	[6]  = TranslateCap('tint_classic_blue'),
	[7]  = TranslateCap('tint_classic_earth'),
	[8]  = TranslateCap('tint_classic_brown_black'),
	[9]  = TranslateCap('tint_contrast_red'),
	[10] = TranslateCap('tint_contrast_blue'),
	[11] = TranslateCap('tint_contrast_yellow'),
	[12] = TranslateCap('tint_contrast_orange'),
	[13] = TranslateCap('tint_bold_pink'),
	[14] = TranslateCap('tint_bold_purple_yellow'),
	[15] = TranslateCap('tint_bold_orange'),
	[16] = TranslateCap('tint_bold_green_purple'),
	[17] = TranslateCap('tint_bold_red_feat'),
	[18] = TranslateCap('tint_bold_green_feat'),
	[19] = TranslateCap('tint_bold_cyan_feat'),
	[20] = TranslateCap('tint_bold_yellow_feat'),
	[21] = TranslateCap('tint_bold_red_white'),
	[22] = TranslateCap('tint_bold_blue_white'),
	[23] = TranslateCap('tint_metallic_gold'),
	[24] = TranslateCap('tint_metallic_platinum'),
	[25] = TranslateCap('tint_metallic_gray_lilac'),
	[26] = TranslateCap('tint_metallic_purple_lime'),
	[27] = TranslateCap('tint_metallic_red'),
	[28] = TranslateCap('tint_metallic_green'),
	[29] = TranslateCap('tint_metallic_blue'),
	[30] = TranslateCap('tint_metallic_white_aqua'),
	[31] = TranslateCap('tint_metallic_orange_yellow'),
	[32] = TranslateCap('tint_metallic_red_yellow')
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +	{name = 'WEAPON_CERAMICPISTOL', label = TranslateCap('weapon_ceramicpistol'), tints = Config.DefaultWeaponTints['non_mk2'], components = {}, ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO
```suggestion
	{name = 'WEAPON_CERAMICPISTOL', label = TranslateCap('weapon_ceramicpistol'), tints = Config.DefaultWeaponTints, components = {}, ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO_PISTOL`}},
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +	{name = 'WEAPON_GADGETPISTOL', label = TranslateCap('weapon_gadgetpistol'), tints = Config.DefaultWeaponTints['non_mk2'], components = {}, ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO_P
```suggestion
	{name = 'WEAPON_DOUBLEACTION', label = TranslateCap('weapon_doubleaction'), tints = Config.DefaultWeaponTints, components = {}, ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO_PISTOL`}},
	{name = 'WEAPON_NAVYREVOLVER', label = TranslateCap('weapon_navyrevolver'), tints = Config.DefaultWeaponTints, components = {}, ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO_PISTOL`}},
	{name = 'WEAPON_FLAREGUN', label = TranslateCap('weapon_flaregun'), tints = Config.DefaultWeaponTints], components = {}, ammo = {label = TranslateCap('ammo_flaregun'), hash = `AMMO_FLAREGUN`}},
	{name = 'WEAPON_GADGETPISTOL', label = TranslateCap('weapon_gadgetpistol'), tints = Config.DefaultWeaponTints, components = {}, ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO_PISTOL`}},
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['mk2'],
```suggestion
		tints = Config.MK2WeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +	{name = 'WEAPON_MARKSMANPISTOL', label = TranslateCap('weapon_marksmanpistol'), tints = Config.DefaultWeaponTints['non_mk2'], components = {}, ammo = {label = TranslateCap('ammo_rounds'), hash = `AM
```suggestion
	{name = 'WEAPON_MARKSMANPISTOL', label = TranslateCap('weapon_marksmanpistol'), tints = Config.DefaultWeaponTints, components = {}, ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO_PISTOL`}},
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['mk2'],
```suggestion
		tints = Config.MK2WeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['mk2'],
```suggestion
		tints = Config.MK2WeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +	{name = 'WEAPON_RAYPISTOL', label = TranslateCap('weapon_raypistol'), tints = Config.DefaultWeaponTints['non_mk2'], components = {}},
```suggestion
	{name = 'WEAPON_STUNGUN', label = TranslateCap('weapon_stungun'), tints = Config.DefaultWeaponTints, components = {}},
	{name = 'WEAPON_RAYPISTOL', label = TranslateCap('weapon_raypistol'), tints = Config.DefaultWeaponTints, components = {}},
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +	{name = 'WEAPON_AUTOSHOTGUN', label = TranslateCap('weapon_autoshotgun'), tints = Config.DefaultWeaponTints['non_mk2'], components = {}, ammo = {label = TranslateCap('ammo_shells'), hash = `AMMO_SHO
```suggestion
	{name = 'WEAPON_AUTOSHOTGUN', label = TranslateCap('weapon_autoshotgun'), tints = Config.DefaultWeaponTints, components = {}, ammo = {label = TranslateCap('ammo_shells'), hash = `AMMO_SHOTGUN`}},
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +	{name = 'WEAPON_DBSHOTGUN', label = TranslateCap('weapon_dbshotgun'), tints = Config.DefaultWeaponTints['non_mk2'], components = {}, ammo = {label = TranslateCap('ammo_shells'), hash = `AMMO_SHOTGUN
```suggestion
	{name = 'WEAPON_DBSHOTGUN', label = TranslateCap('weapon_dbshotgun'), tints = Config.DefaultWeaponTints, components = {}, ammo = {label = TranslateCap('ammo_shells'), hash = `AMMO_SHOTGUN`}},
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +	{name = 'WEAPON_MUSKET', label = TranslateCap('weapon_musket'), tints = Config.DefaultWeaponTints['non_mk2'], components = {}, ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO_SHOTGUN`}},
```suggestion
	{name = 'WEAPON_MUSKET', label = TranslateCap('weapon_musket'), tints = Config.DefaultWeaponTints, components = {}, ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO_SHOTGUN`}},
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['mk2'],
```suggestion
		tints = Config.MK2WeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['mk2'],
```suggestion
		tints = Config.MK2WeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +	{name = 'WEAPON_PRECISIONRIFLE', label = TranslateCap('weapon_precisionrifle'), ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO_SNIPER`}, tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
	{name = 'WEAPON_PRECISIONRIFLE', label = TranslateCap('weapon_precisionrifle'), ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO_SNIPER`}, tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +	{name = 'WEAPON_TACTICALRIFLE',label = TranslateCap('weapon_tactilerifle'),ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO_RIFLE`},tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
	{name = 'WEAPON_TACTICALRIFLE',label = TranslateCap('weapon_tactilerifle'),ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO_RIFLE`},tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +	{name = 'WEAPON_RAYMINIGUN', label = TranslateCap('weapon_rayminigun'), tints = Config.DefaultWeaponTints['non_mk2'], components = {}, ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO_MINIG
```suggestion
	{name = 'WEAPON_GRENADELAUNCHER', label = TranslateCap('weapon_grenadelauncher'), tints = Config.DefaultWeaponTints, components = {}, ammo = {label = TranslateCap('ammo_grenadelauncher'), hash = `AMMO_GRENADELAUNCHER`}},
	{name = 'WEAPON_HOMINGLAUNCHER', label = TranslateCap('weapon_hominglauncher'), tints = Config.DefaultWeaponTints, components = {}, ammo = {label = TranslateCap('ammo_rockets'), hash = `AMMO_HOMINGLAUNCHER`}},
	{name = 'WEAPON_MINIGUN', label = TranslateCap('weapon_minigun'), tints = Config.DefaultWeaponTints, components = {}, ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO_MINIGUN`}},
	{name = 'WEAPON_RAILGUN', label = TranslateCap('weapon_railgun'), tints = Config.DefaultWeaponTints, components = {}, ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO_RAILGUN`}},
	{name = 'WEAPON_RPG', label = TranslateCap('weapon_rpg'), tints = Config.DefaultWeaponTints, components = {}, ammo = {label = TranslateCap('ammo_rockets'), hash = `AMMO_RPG`}},
	{name = 'WEAPON_RAYMINIGUN', label = TranslateCap('weapon_rayminigun'), tints = Config.DefaultWeaponTints, components = {}, ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO_MINIGUN`}},
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +	{name = 'WEAPON_COMPACTLAUNCHER', label = TranslateCap('weapon_compactlauncher'), tints = Config.DefaultWeaponTints['non_mk2'], components = {}, ammo = {label = TranslateCap('ammo_grenadelauncher'),
```suggestion
	{name = 'WEAPON_COMPACTLAUNCHER', label = TranslateCap('weapon_compactlauncher'), tints = Config.DefaultWeaponTints, components = {}, ammo = {label = TranslateCap('ammo_grenadelauncher'), hash = `AMMO_GRENADELAUNCHER`}},
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['mk2'],
```suggestion
		tints = Config.MK2WeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['mk2'],
```suggestion
		tints = Config.MK2WeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['mk2'],
```suggestion
		tints = Config.MK2WeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['mk2'],
```suggestion
		tints = Config.MK2WeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['mk2'],
```suggestion
		tints = Config.MK2WeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['mk2'],
```suggestion
		tints = Config.MK2WeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +	{name = 'WEAPON_RAYCARBINE', label = TranslateCap('weapon_raycarbine'), ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO_SMG`}, tints = Config.DefaultWeaponTints['non_mk2'], components = {}
```suggestion
	{name = 'WEAPON_RAYCARBINE', label = TranslateCap('weapon_raycarbine'), ammo = {label = TranslateCap('ammo_rounds'), hash = `AMMO_SMG`}, tints = Config.DefaultWeaponTints, components = {}},
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['mk2'],
```suggestion
		tints = Config.MK2WeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-10 14:26 UTC, iSentrie commented on [esx]/es_extended/config.weapons.lua
> +		tints = Config.DefaultWeaponTints['non_mk2'],
```suggestion
		tints = Config.DefaultWeaponTints,
```

2023-01-13 07:38 UTC, PreacherDev commented
thanks for the work @iSentrie

2023-01-18 14:18 UTC, closed without merging